<h1>Customer.csv</h1>

In [53]:
import numpy as np
import pandas as pd

In [54]:
df = pd.read_csv("C:/Users/Parth/Power_BI/Credit Card Project/customer.csv")

In [55]:
df.columns

Index(['Client_Num', 'Customer_Age', 'Gender', 'Dependent_Count',
       'Education_Level', 'Marital_Status', 'state_cd', 'Zipcode', 'Car_Owner',
       'House_Owner', 'Personal_loan', 'contact', 'Customer_Job', 'Income',
       'Cust_Satisfaction_Score'],
      dtype='object')

In [56]:
df.head()

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1

In [57]:
df.tail()

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
49994,827930645,57,M,0,Graduate,Single,CA,91750,no,no,no,cellular,Selfemployeed,184494,5
49995,827930646,70,M,5,Graduate,Married,TX,91750,yes,no,yes,cellular,Businessman,161388,4
49996,827930647,64,M,5,High School,Married,FL,91750,no,no,no,cellular,Selfemployeed,104621,2
49997,827930648,31,M,0,Post-Graduate,Single,TX,91750,no,yes,no,cellular,White-collar,121713,3
49998,827930649,29,F,0,Graduate,Single,TX,91750,no,yes,no,cellular,Govt,187223,5

In [58]:
df2.shape

(49999, 18)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Client_Num               49999 non-null  int64
 1   Customer_Age             49999 non-null  int64
 2   Gender                   49999 non-null  object
 3   Dependent_Count          49999 non-null  int64
 4   Education_Level          49999 non-null  object
 5   Marital_Status           49999 non-null  object
 6   state_cd                 49999 non-null  object
 7   Zipcode                  49999 non-null  int64
 8   Car_Owner                49999 non-null  object
 9   House_Owner              49999 non-null  object
 10  Personal_loan            49999 non-null  object
 11  contact                  49999 non-null  object
 12  Customer_Job             49999 non-null  object
 13  Income                   49999 non-null  int64
 14  Cust_Satisfaction_Score  49999 non-null  int64
dtypes: int64(6), object(9)
memory usage: 5.7+ MB

In [60]:
df.describe(include="all")

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
count,4.999900e+04,49999.000000,49999,49999.000000,49999,49999,49999,49999.000000,49999,49999,49999,49999,49999,49999.000000,49999.000000
unique,NaN,NaN,2,NaN,6,3,28,NaN,2,2,2,3,6,NaN,NaN
top,NaN,NaN,F,NaN,Graduate,Married,CA,NaN,no,no,no,cellular,Selfemployeed,NaN,NaN
freq,NaN,NaN,29092,NaN,20289,25249,12153,NaN,29802,26573,43611,36799,12772,NaN,NaN
mean,8.099383e+08,46.844197,NaN,2.467509,NaN,NaN,NaN,91670.533831,NaN,NaN,NaN,NaN,NaN,107845.058741,3.047841
std,3.933931e+07,14.116629,NaN,1.638306,NaN,NaN,NaN,1582.195063,NaN,NaN,NaN,NaN,NaN,69861.247997,1.385680
min,7.080821e+08,21.000000,NaN,0.000000,NaN,NaN,NaN,53010.000000,NaN,NaN,NaN,NaN,NaN,1250.000000,1.000000
25%,8.278932e+08,36.000000,NaN,1.000000,NaN,NaN,NaN,91750.000000,NaN,NaN,NaN,NaN,NaN,45445.000000,2.000000
50%,8.279056e+08,47.000000,NaN,2.000000,NaN,NaN,NaN,91750.000000,NaN,NaN,NaN,NaN,NaN,99346.000000,3.000000
75%,8.279181e+08,58.000000,NaN,4.000000,NaN,NaN,NaN,91750.000000,NaN,NaN,NaN,NaN,NaN,168365.000000,4.000000
max,8.279306e+08,73.000000,NaN,5.000000,NaN,NaN,NaN,99504.000000,NaN,NaN,NaN,NaN,NaN,239791.000000,5.000000

In [61]:
df.isnull().sum()
df.isna().sum()

Client_Num                 0
Customer_Age               0
Gender                     0
Dependent_Count            0
Education_Level            0
Marital_Status             0
state_cd                   0
Zipcode                    0
Car_Owner                  0
House_Owner                0
Personal_loan              0
contact                    0
Customer_Job               0
Income                     0
Cust_Satisfaction_Score    0
dtype: int64

In [62]:
df['Client_Num'].is_unique

True

In [63]:
df['contact'] = df['contact'].replace('unknown', 'Not Available')

In [64]:
from sqlalchemy import create_engine, text

engine = create_engine("mysql+pymysql://root:rootuser@localhost:3306/cards")

with engine.connect() as conn:
 result = conn.execute(text("SELECT DATABASE();"))
 print("Connected to:", result.fetchone())

Connected to: ('cards',)

In [65]:
table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

49999

In [66]:
pd.read_sql("SELECT * FROM customer LIMIT 5;", engine)

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,Not Available,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,Not Available,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1

<h1>credit_card.csv</h1>

In [67]:
df2 = pd.read_csv("C:/Users/Parth/Power_BI/Credit Card Project/credit_card.csv")

In [68]:
df2.head()

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87,01-01-2023,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0
1,708083283,Blue,445,1,108,01-01-2023,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0
2,708084558,Blue,140,0,106,01-01-2023,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0
3,708085458,Blue,250,1,150,01-01-2023,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0
4,708086958,Blue,320,1,106,01-01-2023,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1

In [69]:
df2.tail()

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
49994,827930645,Blue,200,1,62,29-10-2023,Week-43,Q4,2023,10345.4,1956,17260,41,0.325,Swipe,Food,3104.67,0
49995,827930646,Blue,475,0,153,16-07-2023,Week-28,Q3,2023,18094.3,2075,7344,30,0.295,Swipe,Bills,1803.98,1
49996,827930647,Blue,125,0,143,20-08-2023,Week-33,Q3,2023,18847.9,761,16474,95,0.728,Chip,Bills,4454.60,0
49997,827930648,Blue,245,0,101,01-10-2023,Week-39,Q4,2023,3989.3,2111,3028,64,0.677,Swipe,Bills,1004.57,1
49998,827930649,Gold,495,0,90,19-11-2023,Week-46,Q4,2023,1660.0,1771,11429,115,0.867,Swipe,Fuel,2108.16,1

In [70]:
df2.shape

(49999, 18)

In [71]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49999 entries, 0 to 49998
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Client_Num             49999 non-null  int64
 1   Card_Category          49999 non-null  object
 2   Annual_Fees            49999 non-null  int64
 3   Activation_30_Days     49999 non-null  int64
 4   Customer_Acq_Cost      49999 non-null  int64
 5   Week_Start_Date        49999 non-null  object
 6   Week_Num               49999 non-null  object
 7   Qtr                    49999 non-null  object
 8   current_year           49999 non-null  int64
 9   Credit_Limit           49999 non-null  float64
 10  Total_Revolving_Bal    49999 non-null  int64
 11  Total_Trans_Amt        49999 non-null  int64
 12  Total_Trans_Vol        49999 non-null  int64
 13  Avg_Utilization_Ratio  49999 non-null  float64
 14  Use Chip               49999 non-null  object
 15  Exp Type               49999 non-null  object
 16  Interest_Earned        49999 non-null  float64
 17  Delinquent_Acc         49999 non-null  int64
dtypes: float64(3), int64(9), object(6)
memory usage: 6.9+ MB

In [72]:
df2.describe(include="all")

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
count,4.999900e+04,49999,49999.000000,49999.000000,49999.000000,49999,49999,49999,49999.0,49999.000000,49999.000000,49999.000000,49999.000000,49999.000000,49999,49999,49999.000000,49999.000000
unique,NaN,4,NaN,NaN,NaN,52,52,4,NaN,NaN,NaN,NaN,NaN,NaN,3,6,NaN,NaN
top,NaN,Blue,NaN,NaN,NaN,26-02-2023,Week-8,Q1,NaN,NaN,NaN,NaN,NaN,NaN,Swipe,Bills,NaN,NaN
freq,NaN,45597,NaN,NaN,NaN,1020,1020,12640,NaN,NaN,NaN,NaN,NaN,NaN,35142,14751,NaN,NaN
mean,8.099383e+08,NaN,291.156123,0.512650,103.984840,NaN,NaN,NaN,2023.0,16080.510478,1240.940739,8461.447689,72.358727,0.454067,NaN,NaN,2086.755861,0.409468
std,3.933931e+07,NaN,118.131000,0.499845,36.293444,NaN,NaN,NaN,0.0,10171.785911,745.624622,5297.585811,35.336075,0.300485,NaN,NaN,1428.544661,0.491741
min,7.080821e+08,NaN,95.000000,0.000000,40.000000,NaN,NaN,NaN,2023.0,1438.300000,0.000000,510.000000,10.000000,0.000000,NaN,NaN,42.140000,0.000000
25%,8.278932e+08,NaN,195.000000,0.000000,75.000000,NaN,NaN,NaN,2023.0,6629.850000,621.000000,3874.000000,43.000000,0.182000,NaN,NaN,759.710000,0.000000
50%,8.279056e+08,NaN,290.000000,1.000000,103.000000,NaN,NaN,NaN,2023.0,15239.800000,1261.000000,7727.000000,71.000000,0.446000,NaN,NaN,1901.340000,0.000000
75%,8.279181e+08,NaN,395.000000,1.000000,133.000000,NaN,NaN,NaN,2023.0,24893.400000,1867.000000,13197.000000,101.000000,0.712000,NaN,NaN,3336.670000,1.000000
max,8.279306e+08,NaN,500.000000,1.000000,172.000000,NaN,NaN,NaN,2023.0,34516.000000,2517.000000,18484.000000,139.000000,1.000000,NaN,NaN,4785.000000,1.000000

In [73]:
df2.isnull().sum()
df2.isna().sum()

Client_Num               0
Card_Category            0
Annual_Fees              0
Activation_30_Days       0
Customer_Acq_Cost        0
Week_Start_Date          0
Week_Num                 0
Qtr                      0
current_year             0
Credit_Limit             0
Total_Revolving_Bal      0
Total_Trans_Amt          0
Total_Trans_Vol          0
Avg_Utilization_Ratio    0
Use Chip                 0
Exp Type                 0
Interest_Earned          0
Delinquent_Acc           0
dtype: int64

In [74]:
df2['Client_Num'].is_unique

True

In [75]:
table_name = "credit_card"
df2.to_sql(table_name, engine, if_exists="replace", index=False)

49999

In [76]:
pd.read_sql("SELECT * FROM credit_card LIMIT 5;", engine)

,Client_Num,Card_Category,Annual_Fees,Activation_30_Days,Customer_Acq_Cost,Week_Start_Date,Week_Num,Qtr,current_year,Credit_Limit,Total_Revolving_Bal,Total_Trans_Amt,Total_Trans_Vol,Avg_Utilization_Ratio,Use Chip,Exp Type,Interest_Earned,Delinquent_Acc
0,708082083,Blue,200,0,87,01-01-2023,Week-1,Q1,2023,3544.0,1661,15149,111,0.469,Chip,Travel,4393.21,0
1,708083283,Blue,445,1,108,01-01-2023,Week-1,Q1,2023,3421.0,2517,992,21,0.736,Swipe,Entertainment,69.44,0
2,708084558,Blue,140,0,106,01-01-2023,Week-1,Q1,2023,8258.0,1771,1447,23,0.214,Chip,Bills,202.58,0
3,708085458,Blue,250,1,150,01-01-2023,Week-1,Q1,2023,1438.3,0,3940,82,0.000,Online,Grocery,236.40,0
4,708086958,Blue,320,1,106,01-01-2023,Week-1,Q1,2023,3128.0,749,4369,59,0.239,Swipe,Fuel,1004.87,1

<h1>both files checking</h1>

In [79]:
common_clients = df[df['Client_Num'].isin(df2['Client_Num'])]

common_clients

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,Not Available,Businessman,202326,3
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,Not Available,Selfemployeed,14235,2
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49994,827930645,57,M,0,Graduate,Single,CA,91750,no,no,no,cellular,Selfemployeed,184494,5
49995,827930646,70,M,5,Graduate,Married,TX,91750,yes,no,yes,cellular,Businessman,161388,4
49996,827930647,64,M,5,High School,Married,FL,91750,no,no,no,cellular,Selfemployeed,104621,2
49997,827930648,31,M,0,Post-Graduate,Single,TX,91750,no,yes,no,cellular,White-collar,121713,3
49998,827930649,29,F,0,Graduate,Single,TX,91750,no,yes,no,cellular,Govt,187223,5

In [80]:
df['Client_Num'].isin(df2['Client_Num']).any()

np.True_

In [81]:
df['Client_Num'].isin(df2['Client_Num']).sum()

np.int64(49999)

In [82]:
common = set(df['Client_Num']).intersection(set(df2['Client_Num']))
print(len(common))

49999